### ISSUE TITLE
Basic usage - tips?

### ISSUE THREAD

**Issue by odelma** [Zn4rK/telldus-live#1]
Hi, this is not an issue, but being new to using Composer etc. could you give some tips on how to proceed with taking this into use? :smile: 

I'm running (trying to  ) this on RPi2 and have managed to install composer etc. requirements and also have now successfully run "sudo composer require paxx/telldus-live=dev-master" (without sudo it complained about permissions to create the vendor directory and without "=dev-master" something about stable branch missing). This created the vendor directory and installed defined requirements. But nothing was loaded from src/Paxx/Telldus - should it have? 

After this I also tried just downloading /Paxx/Telldus/\* and then placing it in /var/www - and then modified the index.php example by adding my keys and a suitable device to test with, but it just gives http error 500 if I try to open the index.php. I'd appreciate any tips on how to proceed!

**Comment by Zn4rK** [comment]
First I would start of by fixing your permissions - something like this should work:

``` bash
sudo chown www-data:www-data -R /var/www
sudo chmod g+rw -R /var/www
sudo chmod g+s -R /var/www
sudo usermod -a -G www-data pi
```

That should add the user pi to the www-data group on a Raspberry Pi. You probably need to reload bash
after adding yourself: `source ~/.bashrc`. If the reload doesn't work, just reboot the Pi.

The absolute easiest way to getting started with composer is to create a file called composer.json in your "working directory". Fill it with this content:

```
{
    "require": {
        "paxx/telldus-live": "dev-master"
    }
}
```

And then running `composer install`.

This is exactly the same as running `composer require paxx/telldus-live=dev-master`, which you've already have done. This should give you all the dependencies needed. 

The examples included will only work if they are executed from the example-directory. What you really should do is just copy `/var/www/vendor/paxx/telldus-live/examples/index.php` to `/var/www/index.php` and then change the second line of that file.

From

``` PHP
<?php
require '../vendor/autoload.php';
```

To

``` PHP
<?php
require 'vendor/autoload.php';
```

If you're still getting a 500-error you should check the error-logs for your webserver. It should give you more details. It's also possible to configure PHP to be more verbose in the error logging, but Google knows that one better.

**Comment by odelma** [comment]
Thanks a lot, got it working now :+1:  But would've taken a lot of time without you help :smile:

Not sure why but initially it still threw the 500-error with "PHP Fatal error:  Call to undefined function GuzzleHttp\Handler\curl_reset() in /var/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78"

I then did a suggested here: http://stackoverflow.com/questions/30844806/socialite-library-throwing-error-curl-reset-undefined-in-laravel-5, i.e replace
`curl_reset($resource);`
with

```
curl_setopt($resource, CURLOPT_HTTPGET, 1);
curl_setopt($resource, CURLOPT_POST, false);
```

My goal is to eventually do some enabling / disabling of schedules based on certain criteria / switches in Domoticz. So far I was just using the given python example to do some basic switching but as there is a lag I'm tempted to try also that with your php approach, it seems very responsive.

Any pointers on how I would use the setJob function for the above mentioned purpose?

`Public function setJob($id=null, $deviceId=null, $options)`

If for example I needed to disable this schedule:
`{"id":"123456789","deviceId":"123456789","method":"2","methodValue":"0","nextRunTime":0,"type":"time","hour":"0","minute":"30","offset":0,"randomInterval":0,"retries":3,"retryInterval":5,"reps":"10","active":"0","weekdays":"1,2,3,4,5,6,7"}`

**Comment by Zn4rK** [comment]
You should really upgrade your PHP-version. That's why you get the error.
Changes in the vendor directory will be overwritten as soon as you do something with composer. 

Regarding your other question, I have no idea how schedules work. I only use the codeswitches. Try reading the link provided in the phpdoc for the setJob-method. 

I'm really sorry I don't have more answers for you. I'm not that deep into home automation just yet. I was just frustrated with the lack of an proper API and wrote a client for Telldus. I bet their forum will have answers for you!

**Comment by odelma** [comment]
Hmm, strange. I originally installed Php 5.6.19 as required by guzzlehttp but still it is not new enough? Well, the schedule itself is quite simple to operate but the php function syntax I was wondering about. I guess the $options part is where I need to be looking at and somehow pass active = 0 / 1 to the function. Just need a bit more time to test it....:smile:

**Comment by odelma** [comment]
Still cannot wrap my head around it. I get that Api.php is called in the devices and device function are called from Paxx/Telldus/Api.php but how should in call something from Paxx/Telldus/Api/Scheduler.php? When authentication is still in Api.php? I cannot do it with something like this I suppose:

```
$api = new Paxx\Telldus\Api(array(
    'identifier'      => 'xxx',
    'secret'          => 'yyy',
    'user_identifier' => 'jjj',
    'user_secret'     => 'kkk'
));

// Get all jobs
$jobs = $api->scheduler\jobList();
```

**Comment by Zn4rK** [comment]
No you can't do that :)

I seem to have forgotten to implement a scheduler-method. Look at the Api class and see how all the other methods work in the meantime, and I'll try to push a fix tomorrow.

``` php
public function scheduler() {
        return new Api\Scheduler($this->client);
}
```

**Comment by odelma** [comment]
Ok, thanks! :smile:

**Comment by odelma** [comment]
Thanks again! Got it working now and as a reference for other noobs, this works for enabling (1) or disabling (0) a schedule:

```
?php
require 'vendor/autoload.php';

$api = new Paxx\Telldus\Api(array(
    'identifier'      => 'xxx',
    'secret'          => 'yyy',
    'user_identifier' => 'zzz',
    'user_secret'     => 'kkk'
));


$scheduler = $api->scheduler();
$action = $scheduler->setJob('12345','6789',array('active' => '0'));
```

The above would disable the schedule id (=job id) 12345 for device 6789 (yes, as schedules are tied to a single device or group it is a bit strange that also the device id is required).
